# https://alacritty.org/config-alacritty.html

[window]
dimensions = { columns = 201, lines = 54 }
position = { x = 170, y = 200}
padding = { x = 8, y = 8 }
decorations = "Buttonless"
opacity = 0.80
blur = true
option_as_alt = "Both"

[scrolling]
history = 10000

[font]
normal = { family = "JetBrainsMono Nerd Font", "style" = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", "style" = "Bold" }
size = 14
italic = { family = "JetBrainsMono Nerd Font", "style" = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", "style" = "Bold Italic" }

[colors.normal]
green = "#33cc33"
